#include <stdbool>
#define MAXIMOEVENTOSBUFFER 20
#define LIMITEMOVDEPALANCA 420

#define VACIO 0

enum { NOHAYMOVIMIENTO = 50, UPDERECHA, DOWNDERECHA, UPABAJODERECHA, DOWNABAJODERECHA, UPABAJO, DOWNABAJO, UPABAJOIZQUIERDA, DOWNABAJOIZQUIERDA,
        UPIZQUIERDA, DOWNIZQUIERDA, UPARRIBAIZQUIERDA, DOWNARRIBAIZQUIERDA, UPARRIBA, DOWNARRIBA, UPARRIBADERECHA, DOWNARRIBADERECHA, UPBOTON, DOWNBOTON }


char getInputEvent (void); /* ESTA ES LA FUNCION POR LA CUAL SE LEERAN LOS EVENTOS DE ENTRADA DEL BUFFER, LAS CORRESPONDIENTES SE IDENTIFICAN CON LAS
 CONSTANTES DE ARRIBA */

void * InputEvent(void *); //ESTA ES LA FUNCION QUE SE VA A ASOCIAR AL THREAD CORRESPONDIENTE

void storeInputEvent (char evento); //ESTA FUNCION GUARDA UN EVENTO EN EL BUFFER, PUEDE SER UTIL PUBLICARLA PARA FORZARLE EVENTOS EXTERNOS AL JOYSTICK

int esBufferVacio (void); //DEVUELVE 1 EN EL CASO DE QUE EL BUFFER ESTE VACIO, 1 EN EL CASO CONTRARIO

void keyboardChanges (bool estado, int tecla);

int mouseChanges(bool estado, int evMouseX, int evMouseY);